### ISSUE TITLE
Travis CI compile errors with Perl 5.20,5.22,5.24

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#101]
Things work fine up to Perl 5.18 and then BOOM:

https://travis-ci.org/leto/math--gsl/builds/164220872

```
xs/BLAS_wrap.1.15.c: In function ‘SWIG_AsCharPtrAndSize’:
xs/BLAS_wrap.1.15.c:1602:6: error: ‘bool’ undeclared (first use in this function)
```

**Comment by ambs** [comment]
All tests successful.
This is perl 5, version 24, subversion 0 (v5.24.0) built for darwin-2level

**Comment by leto** [comment]
I am inclined to believe that this is a bug with the Travis CI VM not having access to Perl header files, since me, you and all of CPANtesters can build our code.

**Comment by leto** [comment]
This is because swig 2.0.4 does not support Perl 5.20+ . I am attempting to force Travis to use swig 2.0.12 now, because that is what I have locally.

**Comment by leto** [comment]
Travis CI is passing again: https://travis-ci.org/leto/math--gsl/jobs/164477213
