### ISSUE TITLE
Start using travis-perl helpers

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#104]
https://github.com/travis-perl/helpers

So travis can test against Perl "dev" and "blead"

**Comment by leto** [comment]
This is a nice overview: http://blogs.perl.org/users/graham_knop/2014/10/travis-ci-perl-helpers.html

**Comment by autarch** [comment]
You might find this tool I wrote helpful - https://metacpan.org/release/App-CISetup

**Comment by leto** [comment]
@autarch thanks for the link! Will check it out. This is actually an old issue that can be closed, I came up with a solution for testing against various Perls that seems to be OK for now.
