### ISSUE TITLE
Cache building of GSL in .travis.yml

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#117]
On every commit, we build GSL 1.15/2.0/2.2.1, which takes a bunch of time.

Travis CI now has caching, which could really speed this up:

https://docs.travis-ci.com/user/caching/

Since we are compiling the exact same GSL source for every commit, this could potentially reduce our build times significantly.

**Comment by azhar2005** [comment]
Hi, I would like to take this up and also try out #120 and #104 .

**Comment by leto** [comment]
Sounds great! I would say this issue is the easiest of the three, so I suggest starting here.

**Comment by leto** [comment]
We are now using ccache which brought build times down from about 17 minutes to 10 minutes. 

https://travis-ci.org/leto/math--gsl/builds/165100797

@azhar2005 I suggest trying #104 before #120 because it will be a lot easier

**Comment by azhar2005** [comment]
Hey @leto 
I tried caching the entire /tmp/gsl {1.6 -2.1} folders, that brings down the build times to around 4-5 minutes. 
https://travis-ci.org/azhar2005/math--gsl/builds/165083023

ccache seems like a more elegant solution here, for curiosity sake what possible downsides are there with this approach ?

**Comment by leto** [comment]
@azhar2005 awesome! Please send a PR for caching those directories and I will accept it.

ccache and caching the directories can be used together nicely. Since we know the code we are compiling + caching never changes (they are release tarballs) I don't think there are any downsides.

**Comment by leto** [comment]
@azhar2005 also please add 1.16 to your list of cache directories
