### ISSUE TITLE
Create a CONTRIBUTING.md document

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#118]
Let's make it easier for people to contribute!

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.

**Comment by leto** [comment]
Sounds great, @Subway19 ! You can use https://github.com/leto/math--matrixreal/blob/master/CONTRIBUTING.md as a template.

**Comment by Subway19** [comment]
What details to add in Contributing.md doc?

**Comment by leto** [comment]
You can use the math--matrixreal as a template. Please add a section about testing on Travis CI:

If possible, please enable Travis CI on your fork of math--gsl so that it can run on your branch. It tests Math::GSL across multiple versions of GSL and Perl which will find various bugs.

**Comment by leto** [comment]
@Subway19 you need any help?

**Comment by leto** [comment]
This is done.
