### ISSUE TITLE
Increase travis cache timeout

### ISSUE THREAD

**Issue by dosten** [leto/math--gsl#130]
As you can see here https://docs.travis-ci.com/user/caching/#Setting-the-timeout we can configure the cache timeout, by default the timeout is 3 minutes and each job runs for about 4 minutes right now (and almost one at a time), so the cache "doesn't work" right now, I propose to increase the timeout to 24hs.

**Comment by leto** [comment]
@dosten we saw a huge improvement in build times recently. From 17 minutes to ~10 minutes with ccache and then down to about 5 minutes by caching the /tmp/gsl* directories. It's not clear to me if the timeout is the same as the "cache expiration" time. I think the timeout is to prevent a build from failing if uploading/downloading the cache gets stuck.

**Comment by dosten** [comment]
You are right, closing..
