### ISSUE TITLE
WARNING: the following files are missing in your kit:

### ISSUE THREAD

**Issue by guowenshuai** [leto/math--gsl#139]
I'm want to install Math::GSL on windows.

the problem is 

>Build.bat
Building Math-GSL
Can't find appropriate bindings version, check 'xs' directory, it should contains bindings with version <= current GSL version (1.16) at inc/GSLBuilder.pm line 103.

the same as issues:     https://github.com/leto/math--gsl/issues/41

i don't know what to do next.

why i want to Math::GSL ??

i need to calculate the adjoint and eigenvalues of matrix, but all elements of matrix are complex-number.
The module Math::MatrixReal can't do it.

Because of all examples  in Math::GSL::Matrix are real-number. so i wonder to know whether this module can calculate the complex-number matrix. Thank you!

Best Regards.

**Comment by leto** [comment]
@guowenshuai I suggest using a release from CPAN:

http://metacpan.org/pod/Math::GSL

You can also read the documentation for various modules involving complex numbers there.
