### ISSUE TITLE
Another build failure on Arch, but with the git version.

### ISSUE THREAD

**Issue by anadon** [leto/math--gsl#147]
I am having quite a time trying to get this to work.  This time using the git version.  It looks like 'typemap' not being defined when swig is trying to do something.

https://gist.github.com/anadon/d68437709179a64daa561af2aa595650

**Comment by leto** [comment]
@anadon I suggest using a CPAN release unless you are a developer wanting to work on Math::GSL internals. That way, you avoid using SWIG completely. Latest git master supports up to GSL 2.5, please create new issues for any problems you have. Math::GSL 0.40 will be on CPAN soon with GSL 2.5 support, you probably want that.
