### ISSUE TITLE
swig not running from Build.PL 

### ISSUE THREAD

**Issue by rgarrett7** [leto/math--gsl#148]
On MacOS 10.13.3:  

I installed GSL 2.4 . I installed SWIG using Homebrew.  I can start swig from the command line in a terminal window.  When I run "perl Build.PL" I get the following messages:

perl Build.PL
Checking for GSL using gsl-config
Found GSL 2.4 (via gsl-config) installed in /usr/local/Cellar/gsl/2.4
Checking if cc supports "-Wall"...yes
Checking if cc supports "-Wno-sometimes-uninitialized"...yes
Checking if cc supports "-Wno-unused-function"...yes
Checking if cc supports "-Wno-unused-value"...yes
Checking if cc supports "-Wno-unused-function"...yes
Checking if cc supports "-Wno-unused-variable"...yes
Checking if cc supports "-Wno-gnu"...yes
Checking if cc supports "-g"...yes
WARNING: the following files are missing in your kit:
	lib/Math/GSL/BLAS.pm
	lib/Math/GSL/BSpline.pm
	lib/Math/GSL/CBLAS.pm
... This goes on for quite a list in lib, pm, and xs.  

The script ends with:

Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Math-GSL' version '0.39'
Have a great day!

**Here is swig running:**

$ swig -version

SWIG Version 3.0.12

Compiled with clang++ [x86_64-apple-darwin17.0.0]

Configured options: +pcre

**Comment by leto** [comment]
@rgarrett7 those are actually all just warnings, you will notice it exits successfully. There will be a new version of Math::GSL 0.40 uploaded to CPAN soon, if you want something easier to use. Building from the git repo is mostly geared towards developers wanting to work on Math::GSL internals.

Thanks for your bug report!
