### ISSUE TITLE
Build fails on OS X

### ISSUE THREAD

**Issue by coke** [leto/math--gsl#151]
Installed gls with macports:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
$ gsl-config --version
2.4
$ perl -v | head -3

This is perl 5, version 26, subversion 0 (v5.26.0) built for darwin-2level
(with 2 registered patches, see perl -V for more detail)
$ cpanm --verbose Math::GSL
```

eventually dies with:

```
Undefined symbols for architecture x86_64:
  "_gsl_linalg_hessenberg", referenced from:
      __wrap_gsl_linalg_hessenberg in Linalg_wrap.2.2.1.o
     (maybe you meant: __wrap_gsl_linalg_hessenberg_submatrix, __wrap_gsl_linalg_hessenberg_unpack_accum , __wrap_gsl_linalg_hessenberg_set_zero , __wrap_gsl_linalg_hessenberg , __wrap_gsl_linalg_hessenberg_unpack , __wrap_gsl_linalg_hessenberg_decomp )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error building blib/arch/auto/Math/GSL/Linalg/Linalg.bundle file from 'xs/Linalg_wrap.2.2.1.o' at inc/GSLBuilder.pm line 309.
FAIL
! Installing Math::GSL failed. See /Users/coke/.cpanm/work/1529608783.192/build.log for details. Retry with --force to force install it.
```

**Comment by wbraswell** [comment]
I am not an expert in Math::GSL, my best guess is that perhaps the macports build of GSL is somehow incomplete and missing at least the "_gsl_linalg_hessenberg" symbol...

@coke 
I realize this is not a very convenient request, but can you please uninstall the macports GSL and instead try to build GSL from source?  This would at least tell us if the macports build is incomplete.

https://www.gnu.org/software/gsl/

Thanks in advance!  :-)

**Comment by leto** [comment]
I have never used nor tested Math::GSL with macports, I suggest trying from source or homebrew. Also, `gsl_linalg_hessenberg` is a function that exists, the symbol being missing is a symptom of a larger problem.

Most like, this has to do with GSL 2.4 never being tested with Math::GSL, since it's newer than the last time I touched Math::GSL 😸  The build system is trying to use GSL 2.2 swig bindings on GSL 2.4 and most like something changed that is not compatible.

**Comment by wbraswell** [comment]
@plicease
Is there any way to use the Alien version-checking subsystem to overcome this GSL 2.2 vs 2.4 issue?
(As in, modify Alien::GSL somehow to require the correct version of GSL...)

**Comment by plicease** [comment]
You can blacklist specific versions, though this is easier in the new `alienfile` system, and Alien::GSL is still using ABMB.  @jberger is the owner of that Alien so it is up to him, though I am sure he would accept a reasonable PR that improves things.

**Comment by wbraswell** [comment]
Okay let's see what @jberger says

**Comment by leto** [comment]
@coke I am using the latest git master of Math::GSL successfully on OS X with GSL 2.5 (installed via homebrew), please confirm that it works for you and create a new issue with details, if it does not. Thanks for your bug reports!

**Comment by coke** [comment]
No longer have access to the Mac I used to generate the report.

**Comment by wbraswell** [comment]
@coke 
Aww drat okay then, thanks anyway!
