### ISSUE TITLE
new challenges in supporting GSL 2.5

### ISSUE THREAD

**Issue by djerius** [leto/math--gsl#159]
GSL 2.5 poses a new backwards compatibility challenge. In addition to adding new routines, it adds a new member `work_sze` to the `gsl_spmatrix` structure.  The current framework for backwards compatibility doesn't handle changes to structures.

I've started work on 2.5 here:

https://github.com/djerius/math--gsl/tree/gsl-2.5

**Comment by leto** [comment]
@djerius can we generate 2.5 binding on GSL 2.5 and then copy those to a directory where GSL 2.4 has generated all other versions? Some kind of hack like that might make it possible to make a CPAN release, but it sure would be nice to make something easier on us maintainers 👼

**Comment by djerius** [comment]
@leto Yeah, that would work, but as you mentioned is rather ugly.  I'm hoping there's some SWIG magic that we can use.  I tried to use the `%rename` approach, but without success, probably because it's used too early in the SWIG workflow.

If we can split out structure wrapping from function wrapping, we could wrap all of the structures just once per version of GSL and commit those.   This assumes that we would parse all of the GSL headers, not just a subset of them. (I think they're all parsed, as long as they are in the subsystem list).

**Comment by djerius** [comment]
>I tried to use the `%rename` approach, but without success, probably because it's used too early in the SWIG workflow.

It's possible I did something wrong here.  Some experimentation on a less hairy example is in order.

**Comment by leto** [comment]
@djerius I've never done such SWIG/XS black magic, very cool. Does ver2func need to learn how to handle this now?

**Comment by djerius** [comment]
It shouldn't have to. It should just be adding somethng like `^gsl_spmatrix::work_sze` to the `new` hash for 2.5.  Unfortunately I'm not getting SWIG to pay attention.  More debugging.

**Comment by djerius** [comment]
My C is rusty.  It should be this:
```
%module mymodule

%rename("$ignore") Foo::bar;

%inline %{
  typedef struct {
    int bar;
    int baz;
  } Foo;
%}
```
Unfortunately,  swig no longer ignores `bar`.  
```
% swig -perl5 -I. foo.i && grep wrap_Foo foo_wrap.c
XS(_wrap_Foo_bar_set) {
XS(_wrap_Foo_bar_get) {
XS(_wrap_Foo_baz_set) {
XS(_wrap_Foo_baz_get) {
{"mymodulec::Foo_bar_set", _wrap_Foo_bar_set},
{"mymodulec::Foo_bar_get", _wrap_Foo_bar_get},
{"mymodulec::Foo_baz_set", _wrap_Foo_baz_set},
{"mymodulec::Foo_baz_get", _wrap_Foo_baz_get},

```

**Comment by djerius** [comment]
This is pertinent: https://github.com/swig/swig/issues/609

**Comment by djerius** [comment]
> If we can split out structure wrapping from function wrapping, we could wrap all of the structures just once per version of GSL and commit those.

I don't see an easy way to do this.

**Comment by djerius** [comment]
> This is pertinent: [swig/swig#609](https://github.com/swig/swig/issues/609)

I think I've cobbled together a path forward using the approach in the above link.  This requires a little more smarts than `ver2func` currently has, so I took the opportunity to move (almost) all of the knowledge about GSL version differences into a new Ver2Func class.  This cleans up the code quite a bit.  I'm still haven't added the code that'll get 2.5 up and running, but it should be pretty easy now.

See https://github.com/djerius/math--gsl/tree/gsl-2.5

**Comment by djerius** [comment]
> > This is pertinent: [swig/swig#609](https://github.com/swig/swig/issues/609)
> 
> I think I've cobbled together a path forward using the approach in the above link. This requires a little more smarts than `ver2func` currently has, so I took the opportunity to move (almost) all of the knowledge about GSL version differences into a new Ver2Func class. This cleans up the code quite a bit. I'm still haven't added the code that'll get 2.5 up and running, but it should be pretty easy now.
> 
> See https://github.com/djerius/math--gsl/tree/gsl-2.5

I've updated that branch so that GSL 2.5 is the base version, and so far so good on Travis.

**Comment by leto** [comment]
@djerius very cool! In the past, I believe this happened as well. But it was with one of the oldest supported versions of GSL (1.8 and 1.9 I think), so I just removed support for them. This situation needs something better, like what you have been working on 💯

**Comment by djerius** [comment]
I think we're set for a while.  The hackery used to ignore the changes in the C structures ignores all structure elements named `work_sze` and `work_dbl` regardless of which structure they're in.  This may cause problems in the future.

Anyway, I'm closing this 'cause #160
