### ISSUE TITLE
Support GSL 2.0

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#89]
I have a ```gsl2``` branch going that aims to support the latest GSL release, 2.0. They fiddled with their header files a bit which was causing swig to bomb out early in the compile process. I figured out that a few different subsystems needed ```gsl_inline.h``` to be included and that solved that issue.

GSL has started to wrap the definition of some things in a ```#ifndef GSL_DISABLE_DEPRECATED``` which is giving swig+ld issues. For now I am defining that in our swig files, which routes around things like this:

```
Undefined symbols for architecture x86_64:
  "_gsl_bspline_deriv_alloc", referenced from:
      __wrap_gsl_bspline_deriv_alloc in BSpline_wrap.2.0.o
     (maybe you meant: __wrap_gsl_bspline_deriv_alloc)
  "_gsl_bspline_deriv_free", referenced from:
      __wrap_gsl_bspline_deriv_free in BSpline_wrap.2.0.o
     (maybe you meant: __wrap_gsl_bspline_deriv_free)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error building blib/arch/auto/Math/GSL/BSpline/BSpline.bundle file from 'xs/BSpline_wrap.2.0.o' at inc/GSLBuilder.pm line 277.
```

Currently I am trying to figure out this bug, which doesn't seem to be related to the above constant declaration:

```
Undefined symbols for architecture x86_64:
  "_gsl_multifit_fdfsolver_dif_fdf", referenced from:
      __wrap_gsl_multifit_fdfsolver_dif_fdf in Multifit_wrap.2.0.o
     (maybe you meant: __wrap_gsl_multifit_fdfsolver_dif_fdf)
ld: symbol(s) not found for architecture x86_64
```

**Comment by leto** [comment]
@ambs @tadam can you take a look at this branch and give some help if you have time? I am currently stuck on the `gsl_multifit_fdfsolver_dif_fdf` issue. If I comment out multifit_nlin it then gets stuck on a similar error about 4 sf_legendre functions. None of these are wrapped in any ifdefs. If I comment out the legendre function from the swig interface file compilation finishes.

**Comment by ambs** [comment]
On 08/11/15 00:34, Duke Leto wrote:
> @ambs <https://github.com/ambs> @tadam <https://github.com/tadam> can
> you take a look at this branch and give some help if you have time? I am
> currently stuck on the |gsl_multifit_fdfsolver_dif_fdf| issue. If I
> comment out multifit_nlin it then gets stuck on a similar error about 4
> sf_legendre functions. None of these are wrapped in any ifdefs. If I
> comment out the legendre function from the swig interface file
> compilation finishes.
>
great work, Leto!
I will try to peek in that branch today.
first need to find out if brew already knows about gsl 2.0 :)

See you!

**Comment by leto** [comment]
Thanks @ambs! I briefly looked at updating homebrew for GSL 2.0 but I saw that it required hashes of something (not quite sure what) across 4 versions of OS X:

**Comment by ambs** [comment]
WIll try to poke the formula author, who knows if I have luck!

**Comment by leto** [comment]
Well, I have GSL 2.0 compiling with the latest Math::GSL. Commenting out the test relating to https://github.com/leto/math--gsl/issues/93 gets us Linalg.t running and passing again.

So what is left is to see what is up with the Multifit.t test failures and the remaing SF.t test failures before we can release a Math::GSL that supports GSL 2.0.

**Comment by leto** [comment]
Looks like the SF.t failures are due to this:

http://git.savannah.gnu.org/cgit/gsl.git/commit/?id=de2ed0d0768f6e206f8cc7b07f2842b3f0b17843

We need to special-case our tests for GSL <2.0 and GSL >= 2.0.

**Comment by leto** [comment]
0.37 is released and supports GSL 2.x : https://metacpan.org/release/LETO/Math-GSL-0.37
