### ISSUE TITLE
gsl_sf_bessel_Jn_array does not work

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#90]
Passing arrays tp functions was added a long time ago in https://github.com/leto/math--gsl/commit/1e8eb1c9c108a2297623018d47414419419c116d but it still needs to be applied to various functions. 

Reported by Patrick DUPRÉ:

```
use Math::GSL::SF qw [gsl_sf_bessel_Jn_array] ;
my $Jx = [] ;
gsl_sf_bessel_Jn_array (0, 0, 0, $Jx) ;
```

gives the error `TypeError in method 'gsl_sf_bessel_Jn_array', argument 4 of type 'double *' `

**Comment by leto** [comment]
I have start a "bessel_array" branch that gets things started but the passed in array is not mutated. Could you give it a look @tnishimura and @tadam ? You are my resident XS ninjas. Thanks!

**Comment by leto** [comment]
@ambs do you have any ideas or words of wisdom about this?

**Comment by ambs** [comment]
Will try to give it a look during the weekend!

**Comment by ambs** [comment]
At the moment, no error or output.

**Comment by leto** [comment]
Yes, that is what I was getting on my branch. The issue is the Randist code that uses `array_wrapper` returns a single value instead of modifying the array of doubles that is passed in. My wrapper code needs to be changed to pass the data in by reference instead of by value, I think.

**Comment by ambs** [comment]
Can't we just:

`````
    array_wrapper* gsl_sf_bessel_Jn_array_wrapper(int nmin, int nmax, double x) {
        array_wrapper * wrapper = array_wrapper_alloc(nmax - nmin + 1, awDouble);
        gsl_sf_bessel_Jn_array(nmin,nmax,x, (double*)(wrapper->data));
        return wrapper;
    }
`````

**Comment by ambs** [comment]
with that, and
````
my $Jx = gsl_sf_bessel_Jn_array (0, 1, 1);

print Dumper($Jx);
````
I get 
`````
$VAR1 = [
          '0.765197686557966',
          '0.440050585744933'
        ];
`````

**Comment by ambs** [comment]
as a side note, could not find the documentation on what is the return integer semantic. Error, I imagine?

**Comment by ambs** [comment]
(see bessel_array2 branch)

**Comment by leto** [comment]
Awesome news! I believe it is 1 for error, 0 for success but it doesn't seem to be documented.

Now that we have this, it should be simple to support the other similar functions at:

https://www.gnu.org/software/gsl/manual/html_node/Bessel-Functions.html#Bessel-Functions

**Comment by ambs** [comment]
Yeah, I think that too, that the return int is for error.
Not sure if we can die from XS code. That would be a good way to report exceptions.

Out of time slices for this today, can help a little tomorrow. If you wish, post here news, if you have them, so I can continue from there.

**Comment by leto** [comment]
Thanks @ambs! I have implemented bindings for all array-based Bessel function on my "bessel_array" branch, which error checking of return values. Still working on finishing the tests and docs.

**Comment by ambs** [comment]
@leto++

**Comment by leto** [comment]
Just merged this into master. Everything but `gsl_sf_bessel_kl_scaled_array` is working because it doesn't seem to be found by SWIG. Odd thing is that the XS generated for GSL 2.0 had it from when I was testing that, but it is not found in 1.16.
