### ISSUE TITLE
Generating unnecessary XS

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#98]
We currently generate an XS file for every subsystem and every version of GSL we support, even if that subsystem didn't exist for that version of GSL. For example, Multilarge was added in GSL 2.1 yet we have this:

```
$ du -sh xs/Multilarge_wrap.*
288K	xs/Multilarge_wrap.1.11.c
288K	xs/Multilarge_wrap.1.12.c
288K	xs/Multilarge_wrap.1.13.c
292K	xs/Multilarge_wrap.1.14.c
292K	xs/Multilarge_wrap.1.15.c
392K	xs/Multilarge_wrap.1.16.c
412K	xs/Multilarge_wrap.2.0.c
416K	xs/Multilarge_wrap.2.1.c
416K	xs/Multilarge_wrap.2.2.1.c
416K	xs/Multilarge_wrap.2.2.c
```

Roughly an extra 2MB of XS source goes into our CPAN distribution (before zipping), not to mention the longer compile times when building from scratch with SWIG, for files that will never be used. The Rstat subsystem was added in GSL 2.0 and will cause the same issue https://github.com/leto/math--gsl/issues/95

**Comment by ambs** [comment]
I would suggest to stop supporting anything before 1.16
For version 2, start supporting 2.0, 2.1 and 2.2.1 for now, and decide later on what to do, accordingly with released from GSL team.

**Comment by leto** [comment]
Currently our Travis CI instance has GSL 1.15 and I think I have seen a few CPANTesters reports from 1.15 as well. I agree that supporting 1.11 through 1.14 is a burden, but I don't know how many people actually use Math::GSL with those older GSL versions.

**Comment by ambs** [comment]
Sure, 1.14 or 1.15 is ok :)

**Comment by leto** [comment]
We now only support 1.15 and higher (as of 0.39). Our CPAN dist is now 12MB instead of 19MB and our SWIG compile times are way down.
